import { recurrentArray } from "@music-analyzer/stdlib/src/array-of-array/array-of-array";
import { attribute } from "./attribute";
import { htmlElement } from "./html-element";

export const HTML = {
  // getters
  // get  () { return document.getElementsByTagName("") }
  get base() { return document.getElementsByTagName("base")[0]; },
  get head() { return document.getElementsByTagName("head")[0]; },
  get body() { return document.getElementsByTagName("body")[0]; },
  get title() { return document.getElementsByTagName("title")[0]; },
  // creators
  //(attributes?: attribute, text: string = "", children= empty_elements) { return htmlElement("", attributes, text, children) }
   a(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("a", attributes, text, children); },
   abbr(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("abbr", attributes, text, children); },
   address(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("address", attributes, text, children); },
   area(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("area", attributes, text, children); },
   article(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("article", attributes, text, children); },
   aside(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("aside", attributes, text, children); },
   audio(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("audio", attributes, text, children); },
   b(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("b", attributes, text, children); },
  // static base(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("base", attributes, text, children); },
   bdi(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("bdi", attributes, text, children); },
   bdo(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("bdo", attributes, text, children); },
   blockquote(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("blockquote", attributes, text, children); },
  // static body(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("body", attributes, text, children); },
   br(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("br", attributes, text, children); },
   button(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("button", attributes, text, children); },
   canvas(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("canvas", attributes, text, children); },
   caption(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("caption", attributes, text, children); },
   cite(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("cite", attributes, text, children); },
   code(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("code", attributes, text, children); },
   col(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("col", attributes, text, children); },
   colgroup(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("colgroup", attributes, text, children); },
   data(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("data", attributes, text, children); },
   datalist(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("datalist", attributes, text, children); },
   dd(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("dd", attributes, text, children); },
   del(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("del", attributes, text, children); },
   details(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("details", attributes, text, children); },
   dfn(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("dfn", attributes, text, children); },
   dialog(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("dialog", attributes, text, children); },
   div(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("div", attributes, text, children); },
   dl(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("dl", attributes, text, children); },
   dt(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("dt", attributes, text, children); },
   em(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("em", attributes, text, children); },
   embed(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("embed", attributes, text, children); },
   fieldset(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("fieldset", attributes, text, children); },
   figcaption(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("figcaption", attributes, text, children); },
   figure(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("figure", attributes, text, children); },
   footer(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("footer", attributes, text, children); },
   form(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("form", attributes, text, children); },
   h1(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("h1", attributes, text, children); },
   h2(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("h2", attributes, text, children); },
   h3(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("h3", attributes, text, children); },
   h4(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("h4", attributes, text, children); },
   h5(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("h5", attributes, text, children); },
   h6(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("h6", attributes, text, children); },
  // static head(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("head", attributes, text, children); },
   header(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("header", attributes, text, children); },
   hgroup(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("hgroup", attributes, text, children); },
   hr(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("hr", attributes, text, children); },
   html(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("html", attributes, text, children); },
   i(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("i", attributes, text, children); },
   iframe(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("iframe", attributes, text, children); },
   img(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("img", attributes, text, children); },
   input(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("input", attributes, text, children); },

   input_button(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("input", { ...attributes, type: "button" }, text, children); },
   input_checkbox(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("input", { ...attributes, type: "checkbox" }, text, children); },
   input_color(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("input", { ...attributes, type: "color" }, text, children); },
   input_date(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("input", { ...attributes, type: "date" }, text, children); },
   input_datetime_local(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("input", { ...attributes, type: "datetime-local" }, text, children); },
   input_email(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("input", { ...attributes, type: "email" }, text, children); },
   input_file(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("input", { ...attributes, type: "file" }, text, children); },
   input_hidden(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("input", { ...attributes, type: "hidden" }, text, children); },
   input_image(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("input", { ...attributes, type: "image" }, text, children); },
   input_month(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("input", { ...attributes, type: "month" }, text, children); },
   input_number(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("input", { ...attributes, type: "number" }, text, children); },
   input_password(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("input", { ...attributes, type: "password" }, text, children); },
   input_radio(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("input", { ...attributes, type: "radio" }, text, children); },
   input_range(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("input", { ...attributes, type: "range" }, text, children); },
   input_reset(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("input", { ...attributes, type: "reset" }, text, children); },
   input_search(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("input", { ...attributes, type: "search" }, text, children); },
   input_submit(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("input", { ...attributes, type: "submit" }, text, children); },
   input_tel(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("input", { ...attributes, type: "tel" }, text, children); },
   input_text(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("input", { ...attributes, type: "text" }, text, children); },
   input_time(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("input", { ...attributes, type: "time" }, text, children); },
   input_url(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("input", { ...attributes, type: "url" }, text, children); },
   input_week(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("input", { ...attributes, type: "week" }, text, children); },

   ins(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("ins", attributes, text, children); },
   kbd(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("kbd", attributes, text, children); },
   label(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("label", attributes, text, children); },
   legend(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("legend", attributes, text, children); },
   li(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("li", attributes, text, children); },
   link(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("link", attributes, text, children); },
   main(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("main", attributes, text, children); },
   map(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("map", attributes, text, children); },
   mark(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("mark", attributes, text, children); },
   menu(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("menu", attributes, text, children); },
   meta(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("meta", attributes, text, children); },
   meter(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("meter", attributes, text, children); },
   nav(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("nav", attributes, text, children); },
   noscript(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("noscript", attributes, text, children); },
   object(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("object", attributes, text, children); },
   ol(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("ol", attributes, text, children); },
   optgroup(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("optgroup", attributes, text, children); },
   option(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("option", attributes, text, children); },
   output(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("output", attributes, text, children); },
   p(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("p", attributes, text, children); },
   picture(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("picture", attributes, text, children); },
   pre(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("pre", attributes, text, children); },
   progress(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("progress", attributes, text, children); },
   q(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("q", attributes, text, children); },
   rp(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("rp", attributes, text, children); },
   rt(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("rt", attributes, text, children); },
   ruby(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("ruby", attributes, text, children); },
   s(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("s", attributes, text, children); },
   samp(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("samp", attributes, text, children); },
   script(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("script", attributes, text, children); },
   search(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("search", attributes, text, children); },
   section(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("section", attributes, text, children); },
   select(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("select", attributes, text, children); },
   slot(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("slot", attributes, text, children); },
   small(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("small", attributes, text, children); },
   source(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("source", attributes, text, children); },
   span(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("span", attributes, text, children); },
   strong(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("strong", attributes, text, children); },
   style(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("style", attributes, text, children); },
   sub(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("sub", attributes, text, children); },
   summary(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("summary", attributes, text, children); },
   sup(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("sup", attributes, text, children); },
   table(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("table", attributes, text, children); },
   tbody(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("tbody", attributes, text, children); },
   td(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("td", attributes, text, children); },
   template(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("template", attributes, text, children); },
   textarea(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("textarea", attributes, text, children); },
   tfoot(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("tfoot", attributes, text, children); },
   th(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("th", attributes, text, children); },
   thead(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("thead", attributes, text, children); },
   time(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("time", attributes, text, children); },
  // static title(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("title", attributes, text, children); },
   tr(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("tr", attributes, text, children); },
   track(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("track", attributes, text, children); },
   u(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("u", attributes, text, children); },
   ul(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("ul", attributes, text, children); },
   var(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("var", attributes, text, children); },
   video(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("video", attributes, text, children); },
   wbr(attributes?: attribute, text?: string, children?: recurrentArray<Element>) { return htmlElement("wbr", attributes, text, children); },
};
